
GRAIN_VALID_TYPES = ["segment", "ball"]
GRAIN_TYPES_DIMENSIONS = {
    "ball": 2,
    "segment": 1
}
SAVE_PLOTS = True

MAX_SEGMENT_LENGTH = 0.8
MIN_SEGMENT_LENGTH = 0.7

MAX_CIRC_RAD = 0.3
MIN_CIRC_RAD = 0.2

POISSON_INTENSITY = 100
MARKED = True
MARKS_MODEL = "Lisa"
SPACE_DIMENSION = 2
GRAIN_TYPE = "segment"